[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_sign_column_always = 1
let g:ale_fix_on_save = 1
let g:ale_linters = {
\   'python': ['flake8'],
\   'go': ['gometalinter']
\}
let g:ale_fixers = {
\   'python': ['autopep8'],
\   'go':['gofmt'],
\   'r': ['styler'],
\}
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
" for go
let g:ale_go_gometalinter_options = '--fast --enable=staticcheck --enable=gosimple --enable=unused'
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
colorscheme molokai
'''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'mattesgroeger/vim-bookmarks'
