name: Docker build&push
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Register docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: akriaueno/toolbox
          tags: latest

